# Grafana数据源配置
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
      manageAlerts: true
    secureJsonData:
      tlsSkipVerify: true

  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: tlzn-cns
    user: python
    secureJsonData:
      password: "123456"
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis:6379
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 0
    secureJsonData:
      password: ""

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: 'prometheus'
          matcherRegex: 'traceID=(\w+)'
          name: 'TraceID'
          url: '$${__value.raw}'